/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package day06circlesfractal;

import java.awt.Graphics;
import java.awt.Graphics2D;

/**
 *
 * @author phili
 */
public class CircleFractalPanel extends javax.swing.JPanel {

    /**
     * Creates new form CircleFractalPanel
     */
    public CircleFractalPanel() {
        // initComponents();
    }

    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);
        Graphics2D g2d = (Graphics2D) g.create();
        //get shorter length in getWidth() and getHeight(), use it as the baseline to make sure the triangle is always equilateral
        int baseline = getWidth() <= getHeight() ? getWidth() : getHeight();
        baseline = baseline - 10;//set 10 padding

        int x1 = 5;
        int y1 = 5 + baseline * 50 / 100;
        int x2 = 5 + baseline;
        int y2 = 5 + baseline * 50 / 100;
//        int x3 = 5 +  baseline * 50 / 100;
//        int y3 = 5 +  baseline * 50 / 100;
//        int x4 = 5 +  baseline;
//        int y4 = 5 + baseline * 50 / 100;


        g2d.drawOval(10,100,1000,500);

//        g2d.drawLine(x1, y1, x2, y2);
//        drawFractal(g2d,  x1,  y1,  x2,  y2,  x3,  y3);
//        
//        System.out.println("Triangle edge: " + baseline);
//        System.out.println("Triangle height:" + height);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
