/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package day06trianglefractaleasier;

import java.awt.Graphics;
import java.awt.Graphics2D;

/**
 *
 * @author phili
 */
public class TriangleFractalEasierPanel extends javax.swing.JPanel {

    /**
     * Creates new form TriangleFractalEasierPanel
     */
    public TriangleFractalEasierPanel() {
        //initComponents();
    }

    private class Triangle {

        Point pointA;
        Point pointB;
        Point pointC;
        //an Equilateral Triangle's Height: Math.sqrt(Math.pow(line,2) + Math.pow((1/2)line,2))
        int height =(int) Math.sqrt(
               Math.pow(pointB.x - pointC.x,2) +
               Math.pow((pointB.x - pointC.x)/2, 2)
        );

    }

    private class Point {

        int x =0;
        int y=0;
    }

    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);
        Graphics2D g2d = (Graphics2D) g.create();
        /*
        
         */

        Triangle t = new Triangle();
        t.pointA.x = (int)getWidth() * 1 / 2;
        t.pointA.y = (int)getHeight() * 1 / 20;

        t.pointB.x = (int)getWidth() * 1 / 20;
        t.pointB.y = (int)getHeight() * 19 / 20;

        t.pointC.x = (int)getWidth() * 19 / 20;
        t.pointC.y = (int)getHeight() * 19 / 20;

        //draw line 1 point a-  b
        g2d.drawLine(t.pointA.x, t.pointA.y, t.pointB.x, t.pointB.y);

        //draw line 2 point a-  c
        g2d.drawLine(t.pointA.x, t.pointA.y, t.pointC.x, t.pointC.y);

        //draw line 3 point b-  c
        g2d.drawLine(t.pointB.x, t.pointB.y, t.pointC.x, t.pointC.y);

//        int startX = getWidth() / 20;
//        int endX = getWidth() - getWidth() / 20;
//        int startY = getHeight() / 10;
//        int endY = getHeight() / 10;
//        g2d.drawLine(startX, startY, endX, endY);
//        drawFractal(g2d, startX, endX, startY, endY);
    }

    private void drawFractal(Graphics2D g2d, int startX, int endX, int startY, int endY) {
        //1. Set end recursion condition

        //2. draws the 3 lines
        //3. recursive calls,
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
