/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package day06firstfractal;

import java.awt.Graphics;
import java.awt.Graphics2D;

/**
 *
 * @author phili
 */
public class FractalCanvasPanel extends javax.swing.JPanel {

    /**
     * Creates new form FractalCanvasPanel
     */
    public FractalCanvasPanel() {
        // initComponents();
    }

    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);
        Graphics2D g2d = (Graphics2D) g.create();
        /*
        
        */
        
        int startX=getWidth()/20;
        int endX= getWidth()-getWidth()/20;
        int startY = getHeight()/10;
        int endY = getHeight()/10;
        
                
        g2d.drawLine(startX,startY,endX,endY );
        drawFractal(g2d, startX, endX,  startY,endY);
        
    }

    private void drawFractal(Graphics2D g2d, int startX, int endX, int Y, int stepY) {
        //1. condition when the recursion ends
        int width = endX - startX;
        if (width < 3) {
            return;
        }
        //2. draws the two lines
        Y += stepY;
        g2d.drawLine(startX, Y,(startX + width/3), Y);
        g2d.drawLine(endX - width/3, Y,endX , Y);
        
        //3. recursive calls, one for each line that we just drew
        drawFractal(g2d, startX,startX+width/3,Y,stepY);
         drawFractal(g2d, endX-width/3,endX,Y,stepY);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
