/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package day06directorysize;

import java.io.File;
import java.io.IOException;
import javax.swing.JFileChooser;

/**
 *
 * @author phili
 */
public class Day06DirectorySize extends javax.swing.JFrame {

    File selFile;

    /**
     * Creates new form Day06DirectorySize
     */
    public Day06DirectorySize() {
        initComponents();
    }

//    private int getDirSizeByteNonRecur(File file){
//        //get the parent file directory
//        File[] files = file.listFiles();
//        int dirSizeByte=0;
//        for(File f:files){
//            if (f.isFile()) {
//                System.out.println(f.getName()+"'s size is: "+f.length());
//                dirSizeByte+=f.length();
//            }
//            
//        }
//        return dirSizeByte;
//    }
//    
    private double getDirSizeKbNonRecur(File file) {
        //get the parent file directory
        File[] files = file.listFiles();
        double dirSizeByte = 0.00;
        for (File f : files) {
            if (f.isFile()) {
                double fileLength = f.length();
                dirSizeByte += Math.round(fileLength / 1024 * 100.00) / 100.00;//to caolculate length with 2 decimal places
            }

        }
        return dirSizeByte;
    }

    private double getDirSizeKbRecur(File file) {
        //get the parent file directory
        File[] files = file.listFiles();
        double dirSizeByte = 0;
        for (File f : files) {
            if (f.isDirectory()) {
                dirSizeByte += getDirSizeKbRecur(f);
            } else {
                double fileLength = f.length();
                dirSizeByte += Math.round(fileLength / 1024 * 100.00) / 100.00;//to caolculate length with 2 decimal places
            }

        }

        return dirSizeByte;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jfcFileChooser = new javax.swing.JFileChooser();
        btPickDir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lbDir = new javax.swing.JLabel();
        lbDirSizeNonRecr = new javax.swing.JLabel();
        lbDirSizeRecr = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btPickDir.setText("Pick a directory");
        btPickDir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPickDirActionPerformed(evt);
            }
        });

        jLabel1.setText("Directory Size (non-recursive) kB:");

        jLabel2.setText("Directory Size (recursive) kB:");

        lbDir.setText("...");

        lbDirSizeNonRecr.setText("...");

        lbDirSizeRecr.setText("...");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btPickDir, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2)
                    .addComponent(lbDir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbDirSizeNonRecr)
                    .addComponent(lbDirSizeRecr))
                .addContainerGap(211, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btPickDir)
                .addGap(7, 7, 7)
                .addComponent(lbDir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lbDirSizeNonRecr))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lbDirSizeRecr))
                .addContainerGap(200, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btPickDirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPickDirActionPerformed
//there's a test folder in "../TargetDictory"
//        try {
            JFileChooser fc = new JFileChooser();
            fc.setFileSelectionMode(JFileChooser.FILES_AND_DIRECTORIES);
            int returnVal = fc.showOpenDialog(this);
            if (returnVal == JFileChooser.APPROVE_OPTION) {
                File file = fc.getSelectedFile();

                // int sumKbNonRecur =getDirSizeByteNonRecur(file);
                double sumKbNonRecur = getDirSizeKbNonRecur(file);
                double sumKbRecur = getDirSizeKbRecur(file);

                lbDir.setText(file.getName());
                lbDirSizeNonRecr.setText(String.format("%.2f", sumKbNonRecur));
                lbDirSizeRecr.setText(String.format("%.2f", sumKbRecur));
            }
//        } catch (IOException e) {
//            lbDir.setText("No dir is selected");
//        }
    }//GEN-LAST:event_btPickDirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Day06DirectorySize.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Day06DirectorySize.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Day06DirectorySize.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Day06DirectorySize.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Day06DirectorySize().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btPickDir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JFileChooser jfcFileChooser;
    private javax.swing.JLabel lbDir;
    private javax.swing.JLabel lbDirSizeNonRecr;
    private javax.swing.JLabel lbDirSizeRecr;
    // End of variables declaration//GEN-END:variables

}
